### ISSUE TITLE
なぜかPull requestができない

### ISSUE THREAD

**Issue by kakutagawa** [kakutagawa/SwiftPractice2#4]
さっき、MyMusic1をgitにpushしたんだけど、
それをPull Requestできない。（やり方は覚えているけどその画面に行かない的な）
あと、ターミナルでbrunchをtextのままでやってしまったんだけど、
新しく作ってからgit addとかするべきだったんかな？（と思ってtext2とかいうbrunchを作ったけどイマイチ使い方分からず）

コードを書く以前の問題で、gitの使い方とかがまだ分からんので
また教えてください

**Comment by yossibank** [comment]
同じブランチ(`text`)で作ったなら今あがっているPull Requestに変更差分が入るから新しくは作られへんな。(一番下にコミットした履歴あるし、変更差分も増えてる)
https://github.com/kakutagawa/SwiftPractice2/pull/3

別々でPR作りたかったらブランチは変えなあかん。1PRにつき1branch必要やから。(起点のブランチとその作ったブランチの差分を見るから)
やから、やるとしたら`main`のブランチから`myMusic1`みたいなブランチを作るか、`text`のブランチから`myMusic1`のブランチを作るかやな
